// <auto-generated />
using About.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace About.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20230628065426_a")]
    partial class a
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("About.Models.Embedding", b =>
                {
                    b.Property<string>("EmbeddingID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmbeddingAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingVectors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmbeddingID");

                    b.ToTable("Embedding");
                });

            modelBuilder.Entity("About.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "R001",
                            Name = "User"
                        },
                        new
                        {
                            Id = "R002",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("About.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordConfirmed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            Email = "kevinxi@gmail.com",
                            Name = "Kevin@gmail.com",
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            PasswordConfirmed = "e10adc3949ba59abbe56e057f20f883e"
                        },
                        new
                        {
                            Id = "U002",
                            Email = "marylee@gmail.com",
                            Name = "Mary@gmail.com",
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            PasswordConfirmed = "e10adc3949ba59abbe56e057f20f883e"
                        },
                        new
                        {
                            Id = "U003",
                            Email = "johnwei@gmail.com",
                            Name = "John@gmail.com",
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            PasswordConfirmed = "e10adc3949ba59abbe56e057f20f883e"
                        });
                });

            modelBuilder.Entity("About.Models.UserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "U001",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U002",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R002"
                        });
                });

            modelBuilder.Entity("About.Models.UserRoles", b =>
                {
                    b.HasOne("About.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("About.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("About.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("About.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
